# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLinkedin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_linkedin(self):
    self.driver.get("https://www.linkedin.com/")
    self.driver.set_window_size(1428, 755)
    self.driver.find_element(By.ID, "session_key").click()
    self.driver.find_element(By.ID, "session_key").send_keys("ilya_radinsky@hotmail.com")
    self.driver.find_element(By.ID, "session_password").click()
    self.driver.find_element(By.ID, "session_password").click()
    self.driver.find_element(By.ID, "session_password").send_keys("Wdtnjxtr1!")
    self.driver.find_element(By.CSS_SELECTOR, ".sign-in-form__submit-button").click()
    self.driver.find_element(By.ID, "input__phone_verification_pin").send_keys("433821")
    self.driver.find_element(By.ID, "two-step-submit-button").click()
  
